CREATE TABLE`irs990`.`Organizations`(
  EIN VARCHAR(10)PRIMARYKEY,
  INSTNM VARCHAR(255),
  `YEAR` INT,
  PERCENTAGE_WOMEN_TRUSTEES DOUBLE,
  PERCENTAGE_WOMEN_KEY_EMPLOYEES DOUBLE,
  CEO_REVIEWED_COMPENSATION BOOLEAN,
  OTHER_REVIEWED_COMPENSATION BOOLEAN,
  MALE_TO_FEMALE_PAY_RATIO DOUBLE,
  PRESIDENT_TO_AVERAGE_PAY_RATIO DOUBLE
);
